#FROM openjdk:8-jdk-alpine
FROM openjdk:21-jdk
WORKDIR /app

COPY mvnw .
COPY .mvn .mvn

COPY pom.xm .
COPY src src

RUN ./mvnw package -DskipTests -e

CMD ["java", "-jar", "target/2024_user_api-0.0.1-SNAPSHOT.jar"]